# .zshenv
# executed both for interactive shells and for shell scripts

# PATH=~/Dropbox/env/bin:/usr/local/heroku/bin:$PATH

test -d /sw/bin && source /sw/bin/init.sh

if [ "${BASH-no}" != "no" ]; then
	[ -r /etc/bashrc ] && . /etc/bashrc
fi

HISTFILE=$HOME/.zhist
HISTSIZE=1000000
SAVEHIST=1000000

# export NODE_PATH=/usr/local/lib/node
# export NEKOPATH=/usr/local/lib/neko

# alias s='screen -Rx -p='

# export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home
# export EC2_PRIVATE_KEY=~/Dropbox/Keys/aws/pk-6UVRRYQ7POGZU4UFLFBQJFHGPD77MXEM.pem
# export EC2_CERT=~/Dropbox/Keys/aws/cert-6UVRRYQ7POGZU4UFLFBQJFHGPD77MXEM.pem

export LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 LC_COLLATE=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_MONETARY=en_US.UTF-8 LC_NUMERIC=en_US.UTF-8 LC_TIME=en_US.UTF-8
